### ISSUE TITLE
Scale map tiles when zooming while waiting for new tile images

### ISSUE THREAD

**Issue by lenis0012** [johnpryan/flutter_map#60] opened 2018-06-24 20:38 UTC
When you zoom in/out of the map, it can cause the entire map to disappear for a bit, especially on slow internet connection.

It would be great if the map tiles that have already been retrieved for the area you are zooming in get resized while the app is waiting for the download of the proper res tiles to complete.

As in, when you zoom it, it will zoom the tiles in as "placeholder" from the closest scale found in the cache.

Thanks for the amazing work =)

**Comment by johnpryan** [comment] 2019-07-28 05:42
dupe of #79

**Closed by johnpryan** 2019-07-28 05:42 UTC
Labels: enhancement
