### ISSUE TITLE
Unsnap from north

### ISSUE THREAD

**Issue by stafyniaksacha** [johnpryan/flutter_map#210] opened 2019-01-17 06:41 UTC
It seem there is no options about setting custom map orientation, which default to the north.
Does any features is planed to implement this ? I'll take deeper look into if not !

**Comment by johnpryan** [comment] 2019-01-19 16:15
I think this is a dupe of https://github.com/johnpryan/flutter_map/issues/116

**Closed** 2019-01-19 22:38 UTC
