### ISSUE TITLE
hasGesture is always false

### ISSUE THREAD

**Issue by jaysson** [johnpryan/flutter_map#247] opened 2019-03-14 10:50 UTC
Even when I drag the map/pan, the onPositionChanged callback is called with hasGesture false.
```dart
_onMapMove(MapPosition position, bool hasGesture) {
    print("Position has gesture: ${position.hasGesture}");
    print("Has gesture $hasGesture");
}

FlutterMap(
                    mapController: _mapController,
                    options: MapOptions(
                        onPositionChanged: _onMapMove,
                        center: LatLng(12.9732026, 77.6020568),
                        zoom: 16),
                    layers: [
                      TileLayerOptions(
                        urlTemplate:
                            "https://{s}.base.maps.api.here.com/maptile/2.1/maptile/newest/reduced.day/"
                            "{z}/{x}/{y}/256/png8?app_id={appId}&app_code={appCode}",
                        additionalOptions: {"appId": appId, "appCode": appCode},
                        subdomains: ['1', '2', '3', '4'],
                      )
                    ],
                  )
```

**Comment by jaysson** [comment] 2019-03-14 11:09
Changing line no. 63 in gestures.dart:
```
- map.move(newCenter, newZoom);
+ map.move(newCenter, newZoom, hasGesture: true);
```
Makes it work. Is there any problem changing it?

**Comment by johnpryan** [comment] 2019-05-17 18:46
I think we need to rethink `map.move()` since it has `hasGesture` and `isUserGesture`. Created https://github.com/johnpryan/flutter_map/issues/280 to track.

For now feel free to make a pull request

**Comment by johnpryan** [comment] 2019-05-17 18:50
dupe of https://github.com/johnpryan/flutter_map/issues/241

**Closed by johnpryan** 2019-05-17 18:50 UTC
Labels: bug
