### ISSUE TITLE
latest dart release possible causing an issue with flutter_map?

### ISSUE THREAD

**Issue by hfaouaz** [johnpryan/flutter_map#303] opened 2019-06-02 20:11 UTC
Hello,
  After I updated to the latest Dart release, I am starting to get the following error while attempting to run my application.  

Compiler message:
lib/components/map.dart:57:40: Error: The argument type 'Null Function(MapPosition, bool)' can't be assigned to the parameter type 'void Function(MapPosition, bool,
bool)'.
 - 'MapPosition' is from 'package:flutter_map/flutter_map.dart'
 ('file:///Users/....../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/flutter_map.dart').
Try changing the type of the parameter, or casting the argument to 'void Function(MapPosition, bool, bool)'.
                    onPositionChanged: (position, bool) {
                                       ^
lib/components/map_results.dart:101:46: Error: The argument type 'Null Function(MapPosition, bool)' can't be assigned to the parameter type 'void Function(MapPosition,
bool, bool)'.
 - 'MapPosition' is from 'package:flutter_map/flutter_map.dart'
 ('file:///Users/....../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/flutter_map.dart').
Try changing the type of the parameter, or casting the argument to 'void Function(MapPosition, bool, bool)'.
                          onPositionChanged: (position, bool) {
                                             ^
file:///Users/....../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type
'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/...../flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {

**Comment by rezaboroun110** [comment] 2019-06-02 20:59
Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'
please help.
I did not understand anything from the above

**Comment by quantosapplications** [comment] 2019-06-03 14:34
I had the same problem working with the latest version of flutter.
So I switched to the stable branch of flutter and it worked.

For switching version to stable:
- go in you flutter install directory (in Mac OS /Users/me/Library/flutter)
- run `git checkout stable`
- run `flutter doctor`

**Comment by sjmcdowall** [comment] 2019-06-03 20:49
I am having (similar) issues after upgrading to the latest Dart/Flutter combo -- here is a dump in case it helps figure this out:

```
Compiler message:
file:///Users/sjm/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the
parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///Users/sjm/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/overlay_image_layer.dart:40:27: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter
type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.removeListener(listener);
                          ^
file:///Users/sjm/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/overlay_image_layer.dart:43:22: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter
type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
  stream.addListener(listener);
                     ^
file:///Users/sjm/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type
'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///Users/sjm/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/sjm/Development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',
                                                                ^
Compiler failed on /Users/sjm/work/carbyne/carbyne_aml_emu/lib/main.dart
Error launching application on iPhone Xʀ.

```

**Comment by sjmcdowall** [comment] 2019-06-03 21:47
BTW -- I can confirm that @quantosapplications solution of reverting back to 'stable' does allow one to compile and run again .. at least for now. I did a 
```
flutter channel stable
```
on my Mac OS to get it there as that seemed the more appropriate way?

**Comment by diegales1** [comment] 2019-06-03 22:20
@quantosapplications  solution working on Debian distributions as well.

**Comment by ehhc** [comment] 2019-06-06 07:49
The problem is addressed in this PR: https://github.com/johnpryan/flutter_map/pull/296

**Comment by ZeBrody** [comment] 2019-06-07 12:48
Got the same problem after upgrading flutter sdk

```
Compiler message:
file:///C:/Users/Yannick/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/Users/Yannick/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/overlay_image_layer.dart:40:27: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.removeListener(listener);
                          ^
file:///C:/Users/Yannick/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_map-0.5.3+1/lib/src/layer/overlay_image_layer.dart:43:22: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
  stream.addListener(listener);
                     ^
file:///C:/Users/Yannick/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/Users/Yannick/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Flutter%20SDK/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',
                                                                ^
```

Flutter Doctor output:
> [√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale de-AT)
>     • Flutter version 1.6.3 at C:\Flutter SDK\flutter
>     • Framework revision bc7bc94083 (2 weeks ago), 2019-05-23 10:29:07 -0700
>     • Engine revision 8dc3a4cde2
>     • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
>

**Comment by johnpryan** [comment] 2019-06-07 14:44
are you using `flutter_map` `0.6.0` or `0.5.x`?

**Comment by sjmcdowall** [comment] 2019-06-07 16:08
@johnpryan It was 0.5.x for me -- didn't see the update -- I can confirm with the 0.6.x version it's all happy now!

**Comment by johnpryan** [comment] 2019-06-07 16:10
ok, great! thanks for testing

**Closed by johnpryan** 2019-06-07 16:10 UTC
