### ISSUE TITLE
Map Crashes on max zoom out.

### ISSUE THREAD

**Issue by GeoffGodwin** [johnpryan/flutter_map#375] opened 2019-07-27 17:55 UTC
Not sure if anyone else has noticed this but I've just started using the project (and flutter in general) and on my first initial creation of the map I noticed that a full zoom out (maximum distance using a touch gesture) will cause the entire map to lock up and stop responding. This is on the current latest version 0.6.1+2.

By not responding I mean that no further gestures function at this point but calls to the map to change tiles still respond. Clicking clustered markers does nothing at this point. Programmatic calls to the mapController to zoom or move also stop working.

I first assumed something I was doing in my app was causing it so I stripped out markers and various tile options but it appears to persist at bare minimum feature set.

**Comment by johnpryan** [comment] 2019-07-28 05:13
This seems like it's related  to #335

**Comment by johnpryan** [comment] 2019-07-28 05:35
This is a dupe of #59

**Closed by johnpryan** 2019-07-28 05:35 UTC
Labels: bug
