### ISSUE TITLE
Dynamic marker clustering

### ISSUE THREAD

**Issue by aytunch** [johnpryan/flutter_map#221] opened 2019-02-04 22:23 UTC
Since Flutter is very promising tech and maps/markers in some sort are in nearly most of the modern apps, I do believe marker clustering should be implemented in flutter_map asap. google_maps_flutter do not have this feature and this can be another distinctive specialty for this library. Can a pull request be made by an experienced developer? I am not sure if I should write this request here but i searched and did't come up with anywhere else.

**Comment by johnpryan** [comment] 2019-02-05 01:58
I'm not sure what you mean by dynamic, but I think this is a dupe of https://github.com/johnpryan/flutter_map/issues/100

**Comment by johnpryan** [comment] 2019-02-05 01:59
Please let me know if I'm misunderstanding. Thanks for your feedback!

**Closed by johnpryan** 2019-02-05 01:59 UTC

**Comment by RaimundWege** [comment] 2019-02-13 11:24
@aytunch have a look at #201 in that I've described a way how to use k-means with flutter_map.

**Comment by lpongetti** [comment] 2019-06-06 13:46
https://github.com/lpongetti/flutter_map_marker_cluster
