### ISSUE TITLE
Tilt

### ISSUE THREAD

**Issue by hussenkewe** [johnpryan/flutter_map#466] opened 2019-11-23 17:38 UTC
is this plugin supports tilt a map ?

**Comment by moovida** [comment] 2019-12-17 14:04
If by tilt you mean placing it in 2.5 or 3D mode, then I would be quite sure this plugin does not.

**Comment by johnpryan** [comment] 2019-12-17 17:33
dupe of https://github.com/johnpryan/flutter_map/issues/220

**Closed by johnpryan** 2019-12-17 17:33 UTC
