### ISSUE TITLE
Getting exception with 0.6.1 - Stream subType Error

### ISSUE THREAD

**Issue by sjmcdowall** [johnpryan/flutter_map#318] opened 2019-06-07 17:56 UTC
I am now getting the red screen of death in my project when I try to display a map --

From VS Code I can see this and I ran it in debug to get a stack trace but a few exceptions were thrown so not sure if this is the proper stack trace or not (all the exceptions where in flutter_map or Location) 

```
flutter: Another exception was thrown: type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'

CircleLayer._build (/Users/sjm/Development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.6.1/lib/src/layer/circle_layer.dart:56)
CircleLayer.build.<anonymous closure> (/Users/sjm/Development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.6.1/lib/src/layer/circle_layer.dart:49)
_LayoutBuilderElement._layout.<anonymous closure> (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/widgets/layout_builder.dart:113)
BuildOwner.buildScope (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/widgets/framework.dart:2294)
_LayoutBuilderElement._layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/widgets/layout_builder.dart:109)
RenderObject.invokeLayoutCallback.<anonymous closure> (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1716)
PipelineOwner._enableMutationsToDirtySubtrees (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:797)
RenderObject.invokeLayoutCallback (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1716)
_RenderLayoutBuilder.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/widgets/layout_builder.dart:207)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
RenderStack.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/stack.dart:510)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
RenderConstrainedBox.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:259)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:105)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:105)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:105)
RenderObject.layout (/Users/sjm/Development/tools/flutter/packages/flutter/lib/src/rendering/object.dart:1620)
```

**Comment by sjmcdowall** [comment] 2019-06-07 18:09
Here is maybe a more complete stack trace that makes sense -- not the 2 exceptions ... 

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════

flutter: The following NoSuchMethodError was thrown building TileLayer(dirty, state: _TileLayerState#7ce72):

flutter: The getter 'scale' was called on null.

flutter: Receiver: null

flutter: Tried calling: scale

flutter:

flutter: When the exception was thrown, this was the stack:

flutter: #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)

flutter: #1      _TileLayerState._createTileWidget 

flutter: #2      _TileLayerState.build 

flutter: #3      StatefulElement.build 

flutter: #4      ComponentElement.performRebuild 

flutter: #5      Element.rebuild 

flutter: #6      ComponentElement._firstBuild 

flutter: #7      StatefulElement._firstBuild 

flutter: #8      ComponentElement.mount 

flutter: #9      Element.inflateWidget 

flutter: #10     MultiChildRenderObjectElement.mount 

flutter: #11     Element.inflateWidget 

flutter: #12     Element.updateChild 

flutter: #13     SingleChildRenderObjectElement.mount 

flutter: #14     Element.inflateWidget 

flutter: #15     Element.updateChild 

flutter: #16     ComponentElement.performRebuild 

flutter: #17     Element.rebuild 

flutter: #18     ComponentElement._firstBuild 

flutter: #19     ComponentElement.mount 

flutter: #20     Element.inflateWidget 

flutter: #21     Element.updateChild 

flutter: #22     SingleChildRenderObjectElement.mount 

flutter: #23     Element.inflateWidget 

flutter: #24     Element.updateChild 

flutter: #25     SingleChildRenderObjectElement.mount 

flutter: #26     Element.inflateWidget 

flutter: #27     Element.updateChild 

flutter: #28     ComponentElement.performRebuild 

flutter: #29     Element.rebuild 

flutter: #30     ComponentElement._firstBuild 

flutter: #31     StatefulElement._firstBuild 

flutter: #32     ComponentElement.mount 

flutter: #33     Element.inflateWidget 

flutter: #34     Element.updateChild 

flutter: #35     ComponentElement.performRebuild 

flutter: #36     Element.rebuild 

flutter: #37     ComponentElement._firstBuild 

flutter: #38     ComponentElement.mount 

flutter: #39     Element.inflateWidget 

flutter: #40     Element.updateChild 

flutter: #41     SingleChildRenderObjectElement.mount 

flutter: #42     Element.inflateWidget 

flutter: #43     Element.updateChild 

flutter: #44     SingleChildRenderObjectElement.mount 

flutter: #45     Element.inflateWidget 

flutter: #46     Element.updateChild 

flutter: #47     ComponentElement.performRebuild 

flutter: #48     Element.rebuild 

flutter: #49     ComponentElement._firstBuild 

flutter: #50     StatefulElement._firstBuild 

flutter: #51     ComponentElement.mount 

flutter: #52     Element.inflateWidget 

flutter: #53     Element.updateChild 

flutter: #54     ComponentElement.performRebuild 

flutter: #55     Element.rebuild 

flutter: #56     ComponentElement._firstBuild 

flutter: #57     ComponentElement.mount 

flutter: #58     Element.inflateWidget 

flutter: #59     Element.updateChild 

flutter: #60     ComponentElement.performRebuild 

flutter: #61     Element.rebuild 

flutter: #62     ComponentElement._firstBuild 

flutter: #63     StatefulElement._firstBuild 

flutter: #64     ComponentElement.mount 

flutter: #65     Element.inflateWidget 

flutter: #66     Element.updateChild 

flutter: #67     _LayoutBuilderElement._layout.<anonymous closure> 

flutter: #68     BuildOwner.buildScope 

flutter: #69     _LayoutBuilderElement._layout 

flutter: #70     RenderObject.invokeLayoutCallback.<anonymous closure> 

flutter: #71     PipelineOwner._enableMutationsToDirtySubtrees 

flutter: #72     RenderObject.invokeLayoutCallback 

flutter: #73     _RenderLayoutBuilder.performLayout 

flutter: #74     RenderObject.layout 

flutter: #75     RenderFlex.performLayout 

flutter: #76     RenderObject.layout 

flutter: #77     RenderPositionedBox.performLayout 

flutter: #78     RenderObject.layout 

flutter: #79     RenderPadding.performLayout 

flutter: #80     RenderObject.layout 

flutter: #81     MultiChildLayoutDelegate.layoutChild 

flutter: #82     _ScaffoldLayout.performLayout 

flutter: #83     MultiChildLayoutDelegate._callPerformLayout 

flutter: #84     RenderCustomMultiChildLayoutBox.performLayout 

flutter: #85     RenderObject._layoutWithoutResize 

flutter: #86     PipelineOwner.flushLayout 

flutter: #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 

flutter: #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 

flutter: #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 

flutter: #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 

flutter: #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 

flutter: #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 

flutter: #96     _invoke  (dart:ui/hooks.dart:220:10)

flutter: #97     _drawFrame  (dart:ui/hooks.dart:178:3)

flutter: (elided 3 frames from package dart:async)

flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

flutter: Another exception was thrown: type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'
```

**Comment by johnpryan** [comment] 2019-06-07 18:29
this is a dupe of https://github.com/johnpryan/flutter_map/issues/319

See the CHANGELOG for details

**Closed** 2019-06-07 18:34 UTC

**Comment by sjmcdowall** [comment] 2019-06-07 18:40
@johnpryan -- How is this a dupe of #319 ??  I am using 0.6.1 and getting this and I don't see (directly anyway) where in the CHANGELOG.md this is mentioned (looking at dart pub) ..

**Comment by johnpryan** [comment] 2019-06-07 19:37
0.5.x releases are compatable with Flutter's `stable` channel, currently
v1.5.4-hotfix.2 and 0.6.x releases (also on the `flutter_map` `dev` branch) is a
version of flutter_map compatible with Flutter's `dev` channel

**Comment by sjmcdowall** [comment] 2019-06-07 19:50
@johnpryan -- What does this have to do with my issue? 

I am running on "flutter channel beta" (so basically dev?) with flutter_map 0.6.1+2 and am getting this error.. 

Do I need to switch to channel dev?  Is "channel beta" not supported then?

**Comment by johnpryan** [comment] 2019-06-07 19:54
the `beta` channel (v1.6.3)  is somewhere in between `stable` and `dev` so I suspect you will need to choose between `stable` (flutter_map 0.6.x) and `dev` (0.5.x)

If I had infinite time, I would add support for all three channels but this is a side project for me and it's difficult to keep track of these things. Is there a reason you can't use stable or dev?

**Comment by sjmcdowall** [comment] 2019-06-07 20:06
I think you have the stable and dev backwards .. I think you should mention in the README.md that it's either stable or dev.  I can do either .. I will revert back to stable again as I don't have anything in dev I need .. Thanks! Let me try stable and 0.5X and get back to you ..

**Comment by johnpryan** [comment] 2019-06-07 20:10
doh, you're right. `stable` = `flutter_map 0.5.x` and `dev` = `0.6.x`

**Comment by sjmcdowall** [comment] 2019-06-07 23:25
Ok -- Reverted back to stable and flutter_map 0.5.X and all is good!  I do think (for now anyway) a bit more explanation as to what version works with what  -- and that NO version works with "channel beta" currently .. 

Thanks!

**Comment by mulderpf** [comment] 2019-07-08 09:01
This is happening for me - I haven't updated my project in a while and just updated to Flutter Beta which is becoming Flutter Stable today or tomorrow (1.7.8-hotfix.2).  I have tried both 0.5 and 0.6 and this keeps happening.

**Comment by johnpryan** [comment] 2019-07-08 16:20
@mulderpf issue created here: https://github.com/johnpryan/flutter_map/issues/352 thanks!

**Comment by DavidKuennen** [comment] 2019-07-09 06:45
This version is the stable channel by now.
