### ISSUE TITLE
Map bounds.contains fail at edges

### ISSUE THREAD

**Issue by Arkangel12** [johnpryan/flutter_map#331] opened 2019-06-14 19:03 UTC
Hello, 

First at all amazing work with the plugin.

i just find a weird behavior, i use map.bound.contains(latlng) so i get the amount of marker i have in the map bounds but if i move to the edget of the map it stop calculating i'm trying  a workaround by the moment and i fee like it nos a huge issue for us right now but i feel like let you know about this behavior.

i gonna left a gif with and what happens in the app, the code works in all the other places i move but fails as soon i reach the edges of the world! 😄 

![Map behavior](https://user-images.githubusercontent.com/29683014/59531761-a02eaf80-8e9b-11e9-92fd-1936f5c6ac20.gif)

**Comment by guillaumeprevost** [comment] 2019-06-19 15:58
Hi, I'm working on the same app as @Arkangel12 and may be able to bring in a bit more information about this bug.

We have noticed that when the bounds of the map become corrupt when passing across the international date line (east bound above 180, or west bound under -180).

Past this point the mapController bounds are incorrect: bounds.north = bounds.south and bounds.east = bounds.west.

In the case of our App, it's likely causing the issue of not finding anyone within the bounds.

**Comment by johnpryan** [comment] 2019-07-23 22:45
Is this a duplicate of #335?

**Comment by johnpryan** [comment] 2019-07-28 05:51
Marking as a dupe of #335

**Closed by johnpryan** 2019-07-28 05:51 UTC
Labels: bug
